resources:
  - name: prod_eng_assignment
    type: GitRepo
    configuration:
      gitProvider: github_integration
      path: tamirdavid/prod_eng_assignment
      branches:
        include: dev

pipelines:
  - name: vfrog_dev_pipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: prod_eng_assignment
        execution:
          onExecute:
            - echo "Hello World!"

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1               # Execute this step after the prior step
        execution:
          onExecute:
            - echo "Goodbye World!"
