resources:
  - name: prod_eng_assignment
    type: GitRepo
    configuration:
      gitProvider: github_integration
      path: tamirdavid/prod_eng_assignment
      branches:
        include: ^{{gitBranch}}$

  - name: image_resource1
    type: Image
    configuration:
      registry: artifactory_integration      # replace with your Artifactory integration
      sourceRepository: docker-local  # required if registry is Artifactory
      imageName: tamird.jfrog.io/vfrog/{{gitBranch}} # replace with your image path and name
      imageTag: latest
      autoPull: true

  - name: myDockerBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_integration
      buildName: vfrog-{{gitBranch}}
      buildNumber: ${run_number}

  - name: myHelmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_integration
      buildName: {{gitBranch}}_helmchart
      buildNumber: ${run_number}

  - name: {{gitBranch}}_helm_chart
    type: HelmChart
    configuration:
        sourceArtifactory: artifactory_integration
        repository: vfrogProdBuilds
        chart: vfrog-helm
        version: latest

pipelines:
      - name: helm_deploy_{{gitBranch}}_vfrog
        type: HelmDeploy
        configuration:
          helmVersion: 3
          releaseName: vfrog
          inputSteps:
            - name: {{gitBranch}}_helm_publish
          flags: --namespace {{gitBranch}} #--debug --set image.repository=${res_image_resource1_imageName} --set image.tag=${run_number} # --set image.tag=${run_number}
          integrations:
            - name: gke_integration
            - name: gke_integration_new
          inputResources:
            - name: {{gitBranch}}_helm_chart1
            #- name: image_resource1
        execution:
          onStart:
            - export HELM_VERSION="3.4.1"
            - curl -LO "https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz"
            - tar -xzf "helm-v$HELM_VERSION-linux-amd64.tar.gz"
            - ln -sf "$PWD/linux-amd64/helm" /usr/local/bin/helm
            - ln -sf "$PWD/linux-amd64/helm" /usr/local/bin/helm3
            - gcloud app update
            - gcloud container clusters get-credentials vfrog --zone europe-west1-c --project vfrog-gke
