resources:
  - name: prod_eng_assignment
    type: GitRepo
    configuration:
      gitProvider: github_integration
      path: tamirdavid/prod_eng_assignment
      branches:
        include: dev

  - name: image_resource
    type: Image
    configuration:
      registry: artifactory_integration      # replace with your Artifactory integration
      sourceRepository: https://tamird.jfrog.io/artifactory/vfrog-dev/  # required if registry is Artifactory
      imageName: vfrog  # replace with your image path and name
      imageTag: latest
      autoPull: true

pipelines:
  - name: vfrog_dev_pipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"

    steps:
      - name: dev_docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: /application/.
          dockerFileName: Dockerfile
          dockerImageName: vfrog-dev/vfrog  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: prod_eng_assignment
          integrations:
            - name: artifactory_integration    # replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: https://tamird.jfrog.io/artifactory/vfrog-dev/
          integrations:
            - name: artifactory_integration    # replace with your artifactory integration
          inputSteps:
            - name: dev_docker_build
          outputResources:
            - name: artifactory_integration

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: dev_docker_build               # Execute this step after the prior step
        execution:
          onExecute:
            - echo "Goodbye World!"
