resources:
  - name: prod_eng_assignment
    type: GitRepo
    configuration:
      gitProvider: github_integration
      path: tamirdavid/prod_eng_assignment
      branches:
        include: dev

  - name: image_resource_new1
    type: Image
    configuration:
      registry: artifactory_integration      # replace with your Artifactory integration
      sourceRepository: vfrog-dev  # required if registry is Artifactory
      imageName: tamird.jfrog.io/vfrog-dev # replace with your image path and name
      imageTag: latest
      autoPull: true

pipelines:
  - name: vfrog_dev_pipeline
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"

    steps:
      - name: dev_docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: /application/.
          dockerFileName: Dockerfile
          dockerImageName: tamird.jfrog.io/vfrog-dev  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: prod_eng_assignment
          integrations:
            - name: artifactory_integration    # replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: vfrog-dev
          integrations:
            - name: artifactory_integration    # replace with your artifactory integration
          inputSteps:
            - name: dev_docker_build
          outputResources:
            - name: image_resource_new1
