apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }} #"vfrog_helm.fullname"
  labels:
    {{- include "vfrog_helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "vfrog_helm.selectorLabels" . | nindent 4 }}




